Accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name='Accounts'

urlpatterns=[

    path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'), 


]

ArezooNameh/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.HomePage.as_view(), name="home"),
    path('admin/', admin.site.urls),
    path('Accounts/', include("Accounts.urls", namespace="Accounts")),
    path('Accounts/', include("django.contrib.auth.urls")),
    path('Posts/', include("Posts.urls", namespace="Posts")),
    path('Groups/',include("Groups.urls", namespace="Groups")),
    path('test/', views.TestPage.as_view(), name="test"),
    path('thanks/', views.ThanksPage.as_view(), name="thanks"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Posts/urls.py
from django.urls import path
from . import views
from django.conf import settings

from django.conf.urls.static import static

app_name='Posts'

urlpatterns = [
    path('', views.PostList.as_view(), name="all"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta charset="utf-8">
    <title>ArezooNameh</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Optional theme -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->

    <!-- Alternative to Bootstrap 3 Glyphicons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/master.css'%}">
    <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <title></title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg bg-dark mynav" role="navigation" id="navbar">
      <div class="container">
        <div class="navbar-nav align-items-center">
          <a class="navbar-brand mynav" href="{% url 'home' %}">Arezooha</a>
        </div>
        <div class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <a class="nav-item nav-link" href="{% url 'Posts:create' %}" class="btn btn-simple">Post</a>
            <a class="nav-item nav-link" href="{% url 'Groups:all' %}" class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'Groups:create' %}" class="btn btn-simple">Create Group</a>
            <a class="nav-item nav-link" href="{% url 'Accounts:logout' %}" class="btn btn-simple">Log out</a>
          {% else %}
            <a class="nav-item nav-link" href="{% url 'Groups:all' %}"class="btn btn-simple">Groups</a>
            <a class="nav-item nav-link" href="{% url 'Accounts:login' %}" class="btn btn-simple">Log in</a>
            <a class="nav-item nav-link" href="{% url 'Accounts:signup' %}" class="btn btn-simple">Sign up</a>
          {% endif %}
        </div>
      </div>
    </nav>
    <div id="stars"></div>
    <div id="stars2"></div>
    <div id="stars3"></div>
  
      {% block content %}

      {% endblock %}

    <canvas id="canvas"></canvas>

        <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

        <!-- Latest compiled and minified jQuery -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

  </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% load static %}



<div id="stars"></div>
<div id="stars2"></div>
<div id="stars3"></div>

      <div class="container embed-responsive embed-responsive-6by1" >
        <h1>Welcome to our life!</h1>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="{% static 'media/Engagement.mp4' %}" allowfullscreen></iframe>
        </div>
      </div>




{% endblock %}

templates/test.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="container">
  <h1>You are now logged in!</h1>
  <h2><a href="{% url 'Groups:all'%}">Go to Groups</a></h2>


  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="3"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="4"></li>

      </ol>

<div class="carousel-inner">
{% for picture in book_list %}
    {% if forloop.first %}
        <div class="carousel-item active  ">

    {% else %}
        <div class="carousel-item  ">

    {% endif %}

    <img src="{{picture.image.url}}" alt="Responsive image" class='img-fluid d-block w-100 h-100'>
</div>



{% endfor %}



<!-- Optional: some overlay text to describe the video -->




{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}